name: Assign the PR creator

on:
  pull_request:
    types: [opened]

jobs:
  auto_assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign the PR creator
      - uses: toshimaru/auto-author-assign@v2.1.1
