name: Check 101

# Run this on all PRs
on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v2.1.1

  check-lesson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if skool.txt exists
        run: |
          if [ ! -f "./skool.txt" ]; then
            echo "Error: skool.txt file not found in the root directory." >&2
            exit 1
          fi

      - name: Check if skool.txt is not empty
        run: |
          if [ ! -s "./skool.txt" ]; then
            echo "Error: skool.txt file is empty." >&2
            exit 1
          fi

      - name: Is the skool name in the list of members?
        run: |
          SKOOL_NAME=$(cat ./skool.txt)
          if [ -z "$SKOOL_NAME" ]; then
            echo "Error: skool.txt is empty." >&2
            exit 1
          fi
          echo "Checking skool.txt content: $SKOOL_NAME"
          RESPONSE=$(curl -s "https://rails.academy/query?sources=skool_name&skool_name[name]=$SKOOL_NAME")
          if [[ "$RESPONSE" != *"$SKOOL_NAME"* ]]; then
            echo "Error: skool name '$SKOOL_NAME' not found in the API response." >&2
            exit 1
          fi
          echo "Success: skool name '$SKOOL_NAME' verified with API!"      

      - name: Success
        run: echo "All checks passed!"
