name: Check 101

# Run this on all PRs
on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v2.1.1

  check-lesson:
    runs-on: ubuntu-latest

    steps:
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Test curl installation
        run: curl --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if skool.txt exists
        run: |
          if [ ! -f "./skool.txt" ]; then
            echo "Error: skool.txt file not found in the root directory." >&2
            exit 1
          fi

      - name: Check if skool.txt is not empty
        run: |
          if [ ! -s "./skool.txt" ]; then
            echo "Error: skool.txt file is empty." >&2
            exit 1
          fi

      - name: Is the skool name in the list of members?
        run: |
          SKOOL_NAME=$(cat ./skool.txt)
          if [ -z "$SKOOL_NAME" ]; then
            echo "Error: skool.txt is empty." >&2
            exit 1
          fi
          echo "Checking skool.txt content: $SKOOL_NAME"

          # Make the API request
          RESPONSE=$(curl -s "https://rails.academy/query?sources=skool_name&skool_name[name]=$SKOOL_NAME")
          CURL_EXIT_CODE=$?
          echo "Curl exit code: $CURL_EXIT_CODE"
          
          if [ "$CURL_EXIT_CODE" -ne 0 ]; then
            echo "Error: curl command failed with exit code $CURL_EXIT_CODE" >&2
            exit 1
          fi

          # Echo the API response for further inspection
          echo "API Response: $RESPONSE"

          # Optionally add further checks for the response content here
          echo "Success: skool name '$SKOOL_NAME' verified with API!"      

      - name: Success
        run: echo "All checks passed!"
